services:
  database:
    container_name: database
    image: 'postgres'
    volumes:
      - data:/data
    env_file:
      - ./env/postgres.env

  backend:
    container_name: duffbeer-app
    build: ./duffbeer/.
    ports:
      - '8080:8080'
    volumes:
      - data:/data
    env_file:
      - ./env/backend.env
    depends_on:
      - database

volumes:
  data:
